{
        "name" : "app",
        "profiles" : [
                "master"
        ],
        "label" : null,
        "version" : "10",
        "state" : null,
        "propertySources" : [
                {
                        "name" : "C:/Users/I310445/Development/Code/MuConSpringBoot/ConfigGitRepo/yml-microservices-config",
                        "source" : {
                                "spring.jpa.generate-ddl" : true,
                                "spring.rabbitmq.host" : "${DOCKER_IP}",
                                "spring.redis.host" : "$DOCKER_IP}",
                                "spring.zipkin.base-url" : "http://${DOCKER_IP}:9411",
                                "spring.sleuth.sampler.percentage" : 1,
                                "spring.sleuth.log.json.enabled" : true,
                                "info.id" : "${spring.application.name}",
                                "server.port" : "${PORT:${SERVER_PORT:0}}"
                                "logging.level.org.springframework.security" : "DEBUG",
                                "endpoints.shutdown.enabled" : true
                        }
                }
        ]
 }

